### PR TITLE
Cleaning / SpeedUp / Bug Correction

### PR DESCRIPTION
**Pull request by TApplencourt**
# Bench

We use QMC=Chem source code. And compare the time for creating all the fortran file and the man page. (Granularity is the second).

## From strach
No file are present in the IRPF90_temp et  IRP_man
- ref:     14.
- new:    8.

## Restart 
All the file are already present in the IRPF90_temp et  IRP_man
- ref:     14.
- new:   5.

# Main Change

## Remove (most of) the global variable.

`irpy_files.py`, now contain the corse control flow.

## Memoization every where
We sue the `irpy` decorator inside the module

## Rewrote of the parallelisation routine.
Wrote a parallel version of map (`parmap`). It replace the old routine.

##  Lazy writing.
- I speed up the lazy writing function (same_file)
- Generalize is utilization

## Remove the copy/pasta code in `irpf90_t.py`

We all many file class like this:
```
class End_doc(Line):
  str="End_doc"
  def __init__(self,i,text,filename):
    Line.__init__(self,i,text,filename)
  def __repr__(self):
      return "%20s:%5d : %s"%("End_doc",self.i,self.text)
```
First we can remove the `__repr__` and put in the in the `Line` class.
End_doc can me rewritten like this:
```
class End_doc(Line):
  str="End_doc"
  def __init__(self,i,text,filename):
    Line.__init__(self,i,text,filename)
```

Then we can use global, and `type` keyword to all the declaration of new type in a loop.
```
    t = 'End_doc'
    globals()[t] = type(t, (Line, ), {})
```

## Remove strip() and lower() in utils.
We can replace them by `str.strip`
```
#Don't work
map(strip,l_string)
#Work
map(str.strip, l_string)
```

## #14 
The root of this issue take place in `touches.py`. More precisely in
```
  if not var_in_main:
      if var.is_touched:
        out += var.toucher
```
We don't want to create a `touch` subroutine for all the variable who are touched (node and parrent) but only for the node.

So in `variable.py`, we add the argument `is_self_touched` for this purpose.

```python
    @irpy.lazy_property_mutable
    def is_self_touched(self):
        return self.is_read

    @irpy.lazy_property
    def is_touched(self):
        '''If any of the children is touched, the variable is touched'''
        ''' Warning, if you touch the dict, the cache will not be invalided'''
        if self.is_self_touched or any(self.cm_d_variable[i].is_touched for i in self.children):
            return True
        else:
            return False
```

`touches.py` can be rewriten like this:
```
    if not var_in_main:
      if var.is_self_touched:
        out += var.toucher
```
# Changing the orderd of folder change the generated code.
This result to slower IRPF90 runtine because the lazy wrote will fail.
Just sort and a uniquify of the list of the file hanlde by the IRPF90 and you are good to go

### CODE REVIEW

**Comment by scemama** [comment]
Can't install irpy!
```
git@github.com:TApplencourt/irpf90.git
Collecting irpy
  Downloading irpy-0.6.2.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 782kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/run/shm/pip-build-au_Oul/irpy/setup.py", line 14, in <module>
        extensions = cythonize(extensions)
      File "/home/scemama/miniconda2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 818, in cythonize
        aliases=aliases)
      File "/home/scemama/miniconda2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 704, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/scemama/miniconda2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 108, in nonempty
        raise ValueError(error_msg)
    ValueError: 'irpy.pyx' doesn't match any files
    
```

**Comment by TApplencourt** [comment]
Really strange... I'm not able to reproduce.
Anyway, I copy a version the IRPy.pyx file inside IRPF90.  So you should have no problem with this dependency anymore.

**Comment by TApplencourt** [comment]
I have soon finish the stable version. 
Close this pull request.

**Comment by scemama** [comment]
Amazing! :+1:

**Pull request closed without merging**
